### ISSUE TITLE
java 端是不是還不完整？

### ISSUE THREAD

**Issue by twmht** [doodoo0006/mnn_mtcnn_cpp#1]
出來是一個空白頁面

看 MainActivity 好像也沒寫什麼

是不是還沒有完成？

**Comment by doodoo0006** [comment]
完整的，第一次点开可能是空白发自我的华为手机-------- 原始邮件 --------发件人： Ming-Hsuan-Tu <notifications@github.com>日期： 2019年9月3日周二 22:38收件人： doodoo0006/mnn_mtcnn_cpp <mnn_mtcnn_cpp@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [doodoo0006/mnn_mtcnn_cpp] java 端是不是還不完整？ (#1)出來是一個空白頁面

看 MainActivity 好像也沒寫什麼

是不是還沒有完成？
