### ISSUE TITLE
One question about multiple person

### ISSUE THREAD

**Issue by xjcvip007** [doodoo0006/mnn_mtcnn_cpp#2]
Thank you for your sharing~ However, I have one question for you, I transfer your cpp code to iOS, but I found code can only found one face no matter how many faces in the image. That's why? Thank you~

**Comment by doodoo0006** [comment]
mult-faces also support,  if one face res is correct,  check if the faces is too small to detect,  attempt to set the scale factor from 0.25 to 0.5 or 1.0.  if still cannot detect  the faces , send the original  picture to email addr 13032153869@163.com，I will check it later at the weekend, thank you.

**Comment by xjcvip007** [comment]
Thank you for your reply, a part of face with rotation can't detect, for example the image below.
![c1b805a0bc73a633ac5602ef26f7088d](https://user-images.githubusercontent.com/16399125/64305664-a88e1680-cfc2-11e9-95e8-ac03ad8ee112.jpg)
