### ISSUE TITLE
如何在window10上编译android  MNN动态库

### ISSUE THREAD

**Issue by jayle19930918** [doodoo0006/mnn_mtcnn_cpp#3]
你好，请问如何window10上编译android  MNN动态库，github的教程我试过了，没能通过。可能是因为ndk版本的问题，我用该项目的libMNN.so编译不过去，我的ndk版本是r16b。

**Comment by doodoo0006** [comment]
我是用的ndk16b版本在ububtu1604上直接编译成功的，或者你可以用我demo里面的先试试看-------- 原始邮件 --------发件人： jayle19930918 <notifications@github.com>日期： 2019年9月9日周一 11:43收件人： doodoo0006/mnn_mtcnn_cpp <mnn_mtcnn_cpp@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [doodoo0006/mnn_mtcnn_cpp] 如何在window10上编译android  MNN动态库 (#3)你好，请问如何window10上编译android  MNN动态库，github的教程我试过了，没能通过。可能是因为ndk版本的问题，我用该项目的libMNN.so编译不过去。

**Comment by jayle19930918** [comment]
你好，我现在对一幅图像就行处理，人脸检测用了项目中的deal函数，libMNN.so也是用的这个项目里的。我的编译环境是windows10，Android Studio 3.2, NDK版本是r16b，该包含的头文件都包含了，但是一直编不过去，卡在resizeTensor这个函数上，把resizeTensor注释掉就能编译了。是不是应该换成ubuntu的Android Studio进行编译呢？

**Comment by doodoo0006** [comment]
在win10上我可以直接编译通过，我在won10上是用的最新版本的Android studio和最新版本的ndk

**Comment by doodoo0006** [comment]
还是再说明一下，mnn的库在Ubuntu1604上编译的，编译时使用了NDK16b。在win10上的编译了完整的demo，我在编译时使用了最新版本的android studio 和最新版本的ndk发自我的华为手机-------- 原始邮件 --------发件人： 13032153869@163.com日期： 2019年9月9日周一 12:08收件人： doodoo0006/mnn_mtcnn_cpp <reply@reply.github.com>主    题： 回复：[doodoo0006/mnn_mtcnn_cpp] 如何在window10上编译android  MNN动态库 (#3)我是用的ndk16b版本在ububtu1604上直接编译成功的，或者你可以用我demo里面的先试试看-------- 原始邮件 --------发件人： jayle19930918 <notifications@github.com>日期： 2019年9月9日周一 11:43收件人： doodoo0006/mnn_mtcnn_cpp <mnn_mtcnn_cpp@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [doodoo0006/mnn_mtcnn_cpp] 如何在window10上编译android  MNN动态库 (#3)你好，请问如何window10上编译android  MNN动态库，github的教程我试过了，没能通过。可能是因为ndk版本的问题，我用该项目的libMNN.so编译不过去。

**Comment by jayle19930918** [comment]
多谢大佬解答！我再好好看看，到底哪边出了问题。
