### ISSUE TITLE
請問 model 是自己 train 的嗎？

### ISSUE THREAD

**Issue by twmht** [doodoo0006/mnn_mtcnn_cpp#4]
請問 model 是用 https://github.com/kpzhang93/MTCNN_face_detection_alignment 還是你自己 train 的呀？

**Comment by doodoo0006** [comment]
不是，论文里给的

**Comment by twmht** [comment]
喔喔

因為本來論文給的是 column major 的，你有特別轉成 row major? 因為我看你沒有特別做 input transpose

類似這個 https://github.com/conanhujinming/matcaffe2caffe

**Comment by doodoo0006** [comment]
有的，参考mtcnn.cpp 362-366行

**Comment by twmht** [comment]
喔喔喔喔

注意到了

感謝

**Comment by twmht** [comment]
@doodoo0006 

不過問個題外話

我在 pc 上跑 opencl 比 cpu 慢，你在移動端上的計算有比較過嗎？

**Comment by doodoo0006** [comment]
PC上慢的原因应该是对应的加速选项没开，安卓端相对于其它是有优势的，还是在mnn群里问问吧^ ^

**Comment by twmht** [comment]
@doodoo0006 

mnn 群最近比較難得到回應，請問你在安卓端跑 mtcnn，gpu 有比 cpu 快嗎? 我看 OPENMP 也有打開，但還是較慢，還有什麼選項是需要被打開的嗎?

**Comment by doodoo0006** [comment]
多做尝试哈
