### ISSUE TITLE
Android编译报错

### ISSUE THREAD

**Issue by TJXUNwu** [doodoo0006/mnn_mtcnn_cpp#5]
你好，我使用你工程，用AS 编译时，报如下错误：
CMakeFiles/mtcnn_demo.dir/src/main/jni/net.cpp.o: In function `Inference_engine::infer_img(cv::Mat&, Inference_engine_tensor&)':
E:\HJAndriod\AndroidStudioProjects\HJFaceMNN\app\.externalNativeBuild\cmake\debug\arm64-v8a/../../../../src/main/jni/net.cpp:77: undefined reference to `MNN::Interpreter::resizeTensor(MNN::Tensor*, std::vector<int, std::allocator<int> > const&)'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
是链接出错了吗？

**Comment by doodoo0006** [comment]
再仔细检查一下路径吧， 不是用我的工程吧@@， 我好像没有jni文件夹

**Comment by JeanXL** [comment]
您好  编译的时候报这个错
llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1/memory:2339: error: undefined reference to 'MNN::Tensor::~Tensor()'
请问下是什么问题

**Comment by doodoo0006** [comment]
检查一下是否正确包含了MNN头文件和库路径
